// Generator for the household-provenance catalogs, bundled so the classifier runs
// without the local tuning folder. Reads EVERY ~/Documents/Sim Template/*.SimTemplateTuning.xml
// (see feedback_tuning_full_read — never the lazy glob) and writes:
//   src/data/stockPremadeSurnames.ts  — fixed premade surnames (specify_last_name, all files)
//   src/data/stockRoleTraits.ts       — NPC service/role hidden traits (is<Role>), hex-keyed
// Re-run after a new game/pack release to refresh. Usage: npx tsx scripts/diagnostics/buildProvenanceCatalogs.ts
import { readFileSync, readdirSync, writeFileSync } from 'fs';

const TPL_DIR = `${process.env.HOME}/Documents/Sim Template`;
const OUT = `${process.cwd()}/src/data`;

// ---- premade surnames: specify_last_name across ALL tuning files ----
// ---- + solo first names: premades DEFINED surname-less (no_last_name) — Baby
//      Ariel, Mayor Whiskers, the Batuu cast, stray pets, Greg. They're invisible
//      to the surname catalog, so we harvest their fixed first_name instead. ----
const surnames = new Set<string>();
const soloFirstNames = new Set<string>();
for (const f of readdirSync(TPL_DIR)) {
  if (!f.endsWith('.SimTemplateTuning.xml')) continue;
  const xml = readFileSync(`${TPL_DIR}/${f}`, 'utf8');
  for (const m of xml.matchAll(/<T n="specify_last_name">0x[0-9A-Fa-f]+<!--([^>]*)--><\/T>/g)) {
    const label = m[1].trim(); if (label) surnames.add(label.toLowerCase());
  }
  if (xml.includes('no_last_name')) {
    for (const m of xml.matchAll(/<T n="(?:specify_)?first_name">0x[0-9A-Fa-f]+<!--([^>]*)--><\/T>/g)) {
      const label = m[1].trim(); if (label) soloFirstNames.add(label.toLowerCase());
    }
  }
}
// Families absent from the SimTemplate system entirely (baked household binaries,
// 0 tuning mentions): the launch founders + patch-added families (Spencer-Kim-Lewis,
// 2021 base-game refresh). Only the DISTINCTIVE hyphenated surnames — bare Kim/Lewis
// are plausible generated-townie surnames and would false-positive.
const FOUNDER_SUPPLEMENT = ['pancakes', 'caliente', 'lothario', 'spencer-kim', 'kim-lewis', 'spencer-kim-lewis'];
for (const s of FOUNDER_SUPPLEMENT) surnames.add(s);
// Famous premade HOUSEHOLD names that aren't a member surname (the household is named
// thematically — or, Spencer-Kim-Lewis, after ALL its surnames jointly).
const HOUSEHOLD_NAMES = ['bff', 'roomies', 'karaoke legends', 'spencer-kim-lewis'];

const sortedSurnames = [...surnames].sort();
writeFileSync(`${OUT}/stockPremadeSurnames.ts`, `/**
 * Premade-family surname catalog for household origin classification.
 *
 * Generated by scripts/diagnostics/buildProvenanceCatalogs.ts from EVERY
 * ~/Documents/Sim Template/*.SimTemplateTuning.xml (specify_last_name across all
 * ${sortedSurnames.length - FOUNDER_SUPPLEMENT.length} template files — NOT just premadeSimTemplate_*).
 * Used to sub-label an EA household as a recognizable premade vs. a generated townie.
 * Re-run after a new game/pack release to refresh.
 *
 * Founder supplement: ${FOUNDER_SUPPLEMENT.join(', ')} — base-game launch families that
 * predate the SimTemplate system (baked household binaries, 0 tuning mentions).
 */
export const PREMADE_SURNAMES: ReadonlySet<string> = new Set(${JSON.stringify(sortedSurnames)});

/** Premade households named thematically rather than by a member surname. */
export const PREMADE_HOUSEHOLD_NAMES: ReadonlySet<string> = new Set(${JSON.stringify(HOUSEHOLD_NAMES)});

/**
 * Premades DEFINED surname-less in tuning (last_name = no_last_name): Baby Ariel,
 * Mayor Whiskers, the Batuu cast, stray pets, Greg, etc. A member with an EMPTY
 * last name whose first name matches identifies the household as premade — the
 * empty-surname requirement keeps generated townies (always named first+last) out.
 */
export const PREMADE_SOLO_FIRST_NAMES: ReadonlySet<string> = new Set(${JSON.stringify([...soloFirstNames].sort())});
`);

// ---- NPC role/service hidden traits (is<Role>), minus non-role noise ----
// Excluded: not service-NPC roles — gender-customization flag, skill-mastery rewards, vague states.
const EXCLUDE = new Set(['trait_isCustomGender', 'trait_isWeirdo', 'trait_isMasterFisherman',
  'trait_isMasterGardener', 'trait_isMasterHerbalist', 'trait_isMasterChef', 'trait_isMasterVampire']);
const roles = new Map<number, string>();
for (const f of readdirSync(TPL_DIR)) {
  if (!f.endsWith('.SimTemplateTuning.xml')) continue;
  for (const m of readFileSync(`${TPL_DIR}/${f}`, 'utf8').matchAll(/<T>(\d+)<!--(trait_is[A-Za-z]+)-->/g)) {
    if (EXCLUDE.has(m[2])) continue;
    roles.set(Number(m[1]), m[2].replace(/^trait_is/, '').replace(/([a-z])([A-Z])/g, '$1 $2'));
  }
}
const roleEntries = [...roles].sort((a, b) => a[0] - b[0])
  .map(([g, name]) => `  '0x${g.toString(16)}': ${JSON.stringify(name)},`).join('\n');
writeFileSync(`${OUT}/stockRoleTraits.ts`, `/**
 * NPC service/role hidden-trait catalog: trait tuning ID (hex) → role name.
 *
 * Generated by scripts/diagnostics/buildProvenanceCatalogs.ts from is<Role> hidden
 * traits across all SimTemplateTuning files (${roles.size} roles). A sim carrying one of
 * these in its parsed traitIds is the game's current mailman/grim reaper/etc — used to
 * sub-label an EA household as a service NPC. Excludes gender-customization + skill-mastery
 * traits (not service roles). Key format matches STOCK_TRAITS ('0x' + id.toString(16)).
 */
export const ROLE_TRAITS: Record<string, string> = {
${roleEntries}
};
`);

console.log(`Wrote stockPremadeSurnames.ts (${sortedSurnames.length} surnames + ${HOUSEHOLD_NAMES.length} hh-names + ${soloFirstNames.size} solo first names)`);
console.log(`Wrote stockRoleTraits.ts (${roles.size} role traits)`);
