/* Generate src/data/stockTraditions.ts (tradition id -> display name) from the
 * ~/Documents/Holiday S4S export. Filters OUT wedding situationActivity tunings.
 * Validates coverage against tradition IDs actually used across saves.
 * Run: npx tsx scripts/diagnostics/buildStockTraditions.ts */
import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { parseDbpf } from '../../src/lib/dbpf.js';
import { decompressRefpack } from '../../src/lib/refpack.js';
import { scanHolidays } from '../../src/lib/parser/holidays.js';

const DIR = `${process.env.HOME}/Documents/Holiday`;
const files = readdirSync(DIR).filter((f) => f.endsWith('.HolidayTraditionTuning.xml'));

type Entry = { id: string; name: string; tuningName: string };
const kept: Entry[] = [];
const excluded: string[] = [];

for (const f of files) {
  const m = f.match(/!0*([0-9A-Fa-f]+)\.([^.]+)\.HolidayTraditionTuning/);
  if (!m) continue;
  const id = '0x' + m[1].toLowerCase();
  const tuningName = m[2];
  // holiday traditions are named holidayTradition(s)_*; wedding/other = situationActivity_*
  if (!/^holidayTradition/i.test(tuningName)) { excluded.push(tuningName); continue; }
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  const dn = xml.match(/enabled_display_name"[^>]*>\s*0x[0-9A-Fa-f]+<!--(.*?)-->/);
  const name = dn ? dn[1].trim() : `?(${tuningName})`;
  kept.push({ id, name, tuningName });
}
kept.sort((a, b) => parseInt(a.id, 16) - parseInt(b.id, 16));

// observed tradition IDs across all saves (for coverage validation)
const observed = new Set<string>();
const SDIR = `${process.env.HOME}/Documents/Electronic Arts/The Sims 4/saves`;
for (const f of readdirSync(SDIR).filter((x) => x.endsWith('.save'))) {
  try {
    const b = readFileSync(`${SDIR}/${f}`);
    const res = parseDbpf(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
    let blob: Uint8Array | null = null;
    for (const r of res.filter((r) => r.type === 0x0d)) { const d = r.compType === 0xffff ? decompressRefpack(r.data) : r.data; if (!blob || d.length > blob.length) blob = d; }
    if (!blob) continue;
    for (const h of scanHolidays(blob)) for (const t of h.traditions) observed.add('0x' + t.toString(16));
  } catch { /* skip */ }
}
const byId = new Map(kept.map((e) => [e.id, e]));
const missing = [...observed].filter((o) => !byId.has(o));
const noName = kept.filter((e) => e.name.startsWith('?'));

console.log(`kept ${kept.length} holiday traditions; excluded ${excluded.length} non-holiday (wedding/other)`);
console.log(`excluded sample: ${excluded.slice(0, 6).join(', ')}${excluded.length > 6 ? ' ...' : ''}`);
console.log(`observed-in-saves: ${observed.size}; MISSING from catalog: ${missing.length}${missing.length ? ' -> ' + missing.join(', ') : ''}`);
console.log(`entries with no display_name: ${noName.length}${noName.length ? ' -> ' + noName.map((e) => e.tuningName).join(', ') : ''}`);

const body = kept.map((e) => `  '${e.id}': ${JSON.stringify(e.name)},`).join('\n');
const out = `/**
 * Holiday tradition id -> display name. Generated by
 * scripts/diagnostics/buildStockTraditions.ts from a Holiday Tradition tuning
 * export; names are EA's enabled_display_name. Wedding situationActivity
 * tunings (My Wedding Stories) are excluded. DO NOT EDIT BY HAND.
 */
export const STOCK_TRADITIONS: Record<string, string> = {
${body}
};

/** Resolve a tradition tuning id (bigint) to its display name, or null. */
export function resolveTradition(id: bigint): string | null {
  return STOCK_TRADITIONS['0x' + id.toString(16).toLowerCase()] ?? null;
}
`;
writeFileSync('src/data/stockTraditions.ts', out);
console.log(`\nwrote src/data/stockTraditions.ts (${kept.length} entries)`);
