/**
 * Build src/data/stockSkills.ts — skill statistic id → display name.
 *
 * Source: the skill StatisticTuning dump at ~/Documents/Skill. The FILENAME
 * instance hex IS the skill's tuning id (the value a custom-venue "Skill" role
 * criterion stores), so the id→skill mapping is 100% confirmed from filenames.
 *
 * Display name = the skill's tuning name (the filename segment), formatted, plus
 * a small set of CONFIRMED overrides for skills whose in-game name differs from
 * the tuning name (established in the dynasty work). Names that aren't overridden
 * are the tuning name verbatim-formatted — not a guess about which skill it is
 * (that's confirmed), just its rendered name.
 *
 * Run: npx tsx scripts/diagnostics/buildStockSkills.ts
 */
import { readdirSync, writeFileSync } from 'fs';

const DIR = `${process.env.HOME}/Documents/Skill`;
const OUT = 'src/data/stockSkills.ts';

// Confirmed in-game display names that differ from the tuning name.
const OVERRIDE: Record<string, string> = {
  HomestyleCooking: 'Cooking',
  RanchNectar: 'Nectar Making',
  EquestrianSkill: 'Horse Riding',
  ResearchDebate: 'Research & Debate',
  DJMixing: 'DJ Mixing',
  NLS: 'Natural Living',                       // tuning stat_name string (EP19); codename NLS = Natural Living Skill
  All_Ages_Minor_Entomology: 'Entomology',     // in-game skill name
};

// Internal horse hidden-stats that surface through the regex but aren't
// player-facing leveled skills (confirmed with user) — drop from the catalog.
const DROP_RAW = new Set(['Horse_Agility', 'Horse_Endurance', 'Horse_Jumping', 'Horse_Temperament']);

const prettify = (n: string) =>
  n.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2').trim();

// Visible/selectable skills. Match any statistic_Skill_<...> or skill_<Name>,
// stripping the lifestage/category infix for the display name, and EXCLUDING the
// Hidden_* internal skills (Vampire Lore, infant milestones, treadmill, etc.).
// Catches the bare-named pack skills the old regex missed: Archery, Bowling,
// Retail (Sales/WorkEthic/Maintenance), Photography, Fabrication, Veterinarian, …
const RE = /^[0-9A-F]+!000000[0-9A-F]{2}!0*([0-9A-F]+)\.(?:statistic_Skill_(?:(?:AdultMajor|AdultMinor|Child|Toddler|Infant|Retail|Dog|Cat|Pet)_)?|skill_)([A-Za-z0-9_]+)\.StatisticTuning\.xml$/;

const rows: Array<{ id: string; name: string; raw: string }> = [];
for (const f of readdirSync(DIR)) {
  const m = f.match(RE);
  if (!m) continue;
  const raw = m[2];
  if (/^Hidden/.test(raw)) continue; // statistic_Skill_Hidden_* internal skills
  if (DROP_RAW.has(raw)) continue;   // internal horse hidden-stats
  const id = '0x' + parseInt(m[1], 16).toString(16); // normalize: lowercase, no leading zeros
  rows.push({ id, name: OVERRIDE[raw] ?? prettify(raw.replace(/_/g, ' ')), raw });
}
rows.sort((a, b) => a.name.localeCompare(b.name));

const lines = rows.map((r) => `  '${r.id}': ${JSON.stringify(r.name)},`).join('\n');
const file = `/**
 * Skill statistic id → display name. Generated by scripts/diagnostics/buildStockSkills.ts
 * from the ~/Documents/Skill StatisticTuning dump (filename instance = skill id).
 * id→skill is confirmed from filenames; names are the tuning name + confirmed
 * overrides (Cooking, Nectar Making, Horse Riding, Research & Debate, DJ Mixing).
 * DO NOT EDIT BY HAND.
 */
export const STOCK_SKILLS: Record<string, string> = {
${lines}
};
`;
writeFileSync(OUT, file);
console.log(`wrote ${OUT}: ${rows.length} skills`);
for (const need of ['0x4113', '0x413d', '0x19706']) {
  const r = rows.find((x) => x.id === need);
  console.log(`  ${need} -> ${r ? r.name : 'MISSING'}`);
}
