/* Build src/data/stockBusinessPerks.ts — small-business perk TRAIT id -> name.
 * Source: ~/Documents/Small Business trait_SmallBusiness_Perks_* TraitTuning.
 * Perks are stored as TRAITS on the OWNER sim (like earned degrees), so we
 * detect them in a sim's traitIds. id->perk is confirmed from the filename; the
 * name is the prettified codename (the tuning carries no inline display name).
 * Run: npx tsx scripts/diagnostics/buildStockBusinessPerks.ts */
import { readdirSync, writeFileSync } from 'fs';
const DIR = `${process.env.HOME}/Documents/Small Business`;
const pretty = (n: string) => n.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2').trim();
const rows: Array<{ id: string; name: string }> = [];
for (const f of readdirSync(DIR)) {
  const m = f.match(/!0*([0-9A-Fa-f]+)\.trait_SmallBusiness_Perks_([^.]+)\.TraitTuning\.xml$/);
  if (m) rows.push({ id: '0x' + m[1].toLowerCase(), name: pretty(m[2]) });
}
rows.sort((a, b) => a.name.localeCompare(b.name));
const body = rows.map((r) => `  '${r.id}': ${JSON.stringify(r.name)},`).join('\n');
writeFileSync('src/data/stockBusinessPerks.ts', `/**
 * Small-business perk trait id -> display name. Generated by
 * scripts/diagnostics/buildStockBusinessPerks.ts. Perks are stored as TRAITS on
 * the business OWNER sim (confirmed: owners in Slot_10312029 carry these in
 * traitIds), so detect them via the sim's traitIds — same pattern as earned
 * degrees. Names are prettified tuning codenames (no inline display name in the
 * tuning). DO NOT EDIT BY HAND.
 */
export const STOCK_BUSINESS_PERKS: Record<string, string> = {
${body}
};

const PERK_SET = new Set(Object.keys(STOCK_BUSINESS_PERKS));
/** True if a trait id (hex '0x…') is a small-business perk trait. */
export function isBusinessPerkTrait(id: string): boolean { return PERK_SET.has(id.toLowerCase()); }
/** Resolve the small-business perk names from a sim's full trait id list. */
export function businessPerksFromTraits(traitIds: Array<bigint | string>): string[] {
  const out: string[] = [];
  for (const t of traitIds) {
    const id = (typeof t === 'bigint' ? '0x' + t.toString(16) : t).toLowerCase();
    if (PERK_SET.has(id)) out.push(STOCK_BUSINESS_PERKS[id]);
  }
  return out;
}
`);
console.log(`wrote src/data/stockBusinessPerks.ts: ${rows.length} perks`);
