/**
 * Build src/data/stockVenueTraits.ts from the ~/Documents/Traits dump.
 *
 * Custom-venue role criteria of type `trait` reference HIDDEN getaway-NPC role
 * traits (e.g. trait_Hidden_Getaway_NPC_Camp_Camper), NOT the CAS personality
 * traits in stockTraits.ts. Their CONFIRMED in-game name is the `display_name`
 * STBL string, which S4 Studio writes into the XML as a comment — so this is a
 * confirmed mapping (tuning id → real display string), not an inferred one.
 *
 * Run: npx tsx scripts/diagnostics/buildVenueTraits.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';
const HOME = process.env.HOME!;
const DIR = `${HOME}/Documents/Traits`;

const out: Record<string, { name: string; icon: string | null }> = {};
for (const f of readdirSync(DIR)) {
  // Hidden getaway-NPC role traits (the ones premade venue roles require).
  const m = f.match(/!0*([0-9A-F]+)\.trait_Hidden_Getaway[A-Za-z0-9_]*\.TraitTuning\.xml$/);
  if (!m) continue;
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  const dn = xml.match(/n="display_name">[^<]*<!--([^>]*?)-->/);
  const name = dn?.[1]?.trim();
  if (!name) continue; // internal markers with no display string → skip
  // icon ResourceKey instance → /trait-icons/<instance>.png (extracted from icons.html)
  const icon = xml.match(/n="icon"[^>]*>[0-9a-fA-F]{8}:[0-9a-fA-F]{8}:([0-9a-fA-F]{16})</);
  out['0x' + parseInt(m[1], 16).toString(16)] = { name, icon: icon ? icon[1].toLowerCase() : null };
}

const body = Object.entries(out)
  .sort((a, b) => a[1].name.localeCompare(b[1].name))
  .map(([k, v]) => `  '${k}': { name: ${JSON.stringify(v.name)}, icon: ${v.icon ? `'${v.icon}'` : 'null'} },`)
  .join('\n');

writeFileSync('src/data/stockVenueTraits.ts',
  `/**\n` +
  ` * Hidden getaway-NPC role traits referenced by custom-venue role criteria.\n` +
  ` * id -> confirmed in-game display_name (from the TraitTuning STBL comment) + the\n` +
  ` * icon's ResourceKey instance. The PNG files are named by the trait id\n` +
  ` * (/trait-icons/<traitIdHex>.png, written by extractIconsFromHTML.ts); \`icon\` is\n` +
  ` * the has-icon flag + exact ResourceKey provenance, not the filename.\n` +
  ` * Generated by scripts/diagnostics/buildVenueTraits.ts from ~/Documents/Traits.\n` +
  ` * DO NOT EDIT BY HAND. These are distinct from the CAS traits in stockTraits.ts.\n` +
  ` */\nexport interface StockVenueTrait { name: string; icon: string | null }\n` +
  `export const STOCK_VENUE_TRAITS: Record<string, StockVenueTrait> = {\n${body}\n};\n`);

console.log(`stockVenueTraits: ${Object.keys(out).length} traits`);
