// Build the EXACT set of venue types a club can use as a General-Venue hangout,
// for the ClubManager authoring dropdown. Source of truth is the VenueTuning
// `<T n="allowed_for_clubs">True</T>` flag (read from ~/Documents/Venue) — that
// removes all the non-club venues (Police Station, FutureSim Labs, Acting Studio,
// Hospital, …). Two documented overrides on top, confirmed against the in-game
// club-hangout picker (user screenshot, 2026-06-23), since the flag is a slight
// superset:
//   - EXCLUDE: 6 travel/destination venues that carry allowed_for_clubs=True in
//     tuning but never appear in the in-game picker.
//   - RESIDENTIAL: the 4 residential venue types all display as "Club member's
//     house" in the club UI (4 separate ids, 4 house icons).
// Output: src/data/clubHangoutVenues.ts. Run: npx tsx scripts/diagnostics/buildClubVenueChoices.ts
import { readFileSync, readdirSync, writeFileSync } from 'fs';

const VDIR = `${process.env.HOME}/Documents/Venue`;

// allowed_for_clubs=True in tuning but absent from the in-game picker (special
// travel/destination venues). Confirmed via the in-game screenshot.
const EXCLUDE = new Set([
  '0x1e0fc', // Ancient Ruins (Jungle Adventure)
  '0x21c8c', // Center Park (San Myshuno — not selectable as a club venue)
  '0x1e927', // Chalet Gardens (Granite Falls)
  '0x1e88f', // Island Bluff (Sulani)
  '0x33fa0', // The Magic Realm (Realm of Magic)
  '0x32d36', // University Housing (dorms)
]);
// The residential venue types collapse to one display name in the club UI.
const RESIDENTIAL = new Set(['0x6fc6', '0x53533', '0x37f83', '0x3d9dc']);
const RESIDENTIAL_LABEL = "Club member's house";

interface Entry { id: string; label: string }
const entries: Entry[] = [];
for (const f of readdirSync(VDIR)) {
  const m = f.match(/^E6BBD7DE![^!]+!0*([0-9A-Fa-f]+)\..+\.VenueTuning\.xml$/i);
  if (!m) continue;
  const id = '0x' + parseInt(m[1], 16).toString(16);
  const xml = readFileSync(`${VDIR}/${f}`, 'utf8');
  if (!/<T n="allowed_for_clubs">True/.test(xml)) continue;
  if (EXCLUDE.has(id)) continue;
  const dn = xml.match(/<T n="display_name">0x[0-9A-Fa-f]+<!--(.*?)-->/);
  const label = RESIDENTIAL.has(id) ? RESIDENTIAL_LABEL : (dn ? dn[1].trim() : null);
  if (!label) continue;
  entries.push({ id, label });
}
// In-game order is alphabetical by label (residential's 4 group together).
entries.sort((a, b) => a.label.localeCompare(b.label) || a.id.localeCompare(b.id));

console.log(`${entries.length} club-hangout venue types:`);
for (const e of entries) console.log(`  ${e.id.padEnd(9)} ${e.label}`);

const rows = entries.map((e) => `  { id: '${e.id}', label: ${JSON.stringify(e.label)} },`).join('\n');
const labelRows = entries.map((e) => `  '${e.id}': ${JSON.stringify(e.label)},`).join('\n');
writeFileSync('src/data/clubHangoutVenues.ts', `// The exact venue types a club can use as a General-Venue hangout — generated by
// scripts/diagnostics/buildClubVenueChoices.ts from each VenueTuning's
// <T n="allowed_for_clubs"> flag, minus 6 travel/destination venues and with the
// 4 residential types collapsed to "Club member's house" (both confirmed against
// the in-game club-hangout picker). DO NOT EDIT BY HAND. The label is the base
// noun; the UI shows it as "Any <label>". Resolve icons via lotIconUrlById(id).

/** Ordered list for the authoring dropdown (in-game alphabetical order). */
export const CLUB_HANGOUT_VENUES: { id: string; label: string }[] = [
${rows}
];

/** venue id → club-context display label (residential → "Club member's house"). */
export const CLUB_HANGOUT_VENUE_LABEL: Record<string, string> = {
${labelRows}
};
`);
console.log(`\nwrote src/data/clubHangoutVenues.ts (${entries.length} venues)`);
