/* Generate src/data/stockHolidayTraditions.ts — each stock holiday's DEFAULT
 * tradition ids, read from its HolidayDefinitionTuning <L n="traditions">. The
 * save only stores traditions for holidays the player MODIFIED; for everything
 * else these tuning defaults are the effective (in-game) traditions.
 * Run: npx tsx scripts/diagnostics/buildStockHolidayTraditions.ts */
import { readFileSync, readdirSync, writeFileSync } from 'fs';

const DIR = `${process.env.HOME}/Documents/Holiday`;
const files = readdirSync(DIR).filter((f) => f.endsWith('.HolidayDefinitionTuning.xml'));

type Entry = { id: string; tuningName: string; traditions: string[] };
const kept: Entry[] = [];

for (const f of files) {
  const m = f.match(/!0*([0-9A-Fa-f]+)\.([^.]+)\.HolidayDefinitionTuning\.xml$/);
  if (!m) continue;
  const id = '0x' + m[1].toLowerCase();
  const tuningName = m[2];
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  // <L n="traditions"> ... <T>DECIMAL<!--name--></T> ... </L>
  const block = xml.match(/<L n="traditions">([\s\S]*?)<\/L>/);
  const traditions: string[] = [];
  if (block) {
    for (const t of block[1].matchAll(/<T>\s*(\d+)/g)) {
      traditions.push('0x' + parseInt(t[1], 10).toString(16));
    }
  }
  kept.push({ id, tuningName, traditions });
}
kept.sort((a, b) => parseInt(a.id, 16) - parseInt(b.id, 16));

const withTrad = kept.filter((e) => e.traditions.length);
console.log(`holiday definitions: ${kept.length}; with default traditions: ${withTrad.length}`);
for (const e of withTrad.slice(0, 6)) console.log(`  ${e.id} ${e.tuningName}: ${e.traditions.join(', ')}`);

const body = withTrad.map((e) => `  '${e.id.replace(/^0x/, '')}': [${e.traditions.map((t) => `'${t.replace(/^0x/, '')}'`).join(', ')}],`).join('\n');
const out = `/**
 * Stock holiday DEFAULT traditions, keyed by holiday_type (hex, no 0x) →
 * tradition tuning ids (hex, no 0x). Generated by
 * scripts/diagnostics/buildStockHolidayTraditions.ts from the
 * HolidayDefinitionTuning <L n="traditions"> lists. DO NOT EDIT BY HAND.
 *
 * Used to show the effective traditions for holidays the player hasn't
 * customized (the save only stores a traditions list when modified).
 */
export const STOCK_HOLIDAY_TRADITIONS: Record<string, string[]> = {
${body}
};
`;
writeFileSync('src/data/stockHolidayTraditions.ts', out);
console.log(`\nwrote src/data/stockHolidayTraditions.ts (${withTrad.length} entries)`);
