/**
 * Build src/data/skillCriteriaIds.ts — the skills offered by the in-game
 * "criteria" pickers (club membership / small-business customer requirements).
 *
 * Source: the skill StatisticTuning dump at ~/Documents/Skill. Each skill's
 * `<L n="tags">` carries GameplayTags; the game's own visibility flag is
 * `Skill_All_Visible` — it's present on every real, player-facing skill (Cooking,
 * Bowling, Archery, Dancing…) and ABSENT on hidden/retail/non-skill statistics
 * (Sales, Maintenance, Work Ethic, Juice Pong, Ping Pong, Robot Enhancement,
 * milestones). That single tag — NOT skill_level_type (major/minor) — is what
 * separates the real skills.
 *
 * Toddler skills (Skill_Toddler: Potty, Communication, Imagination, Movement,
 * Thinking) are visible but excluded per design; CHILD skills (Mental, Motor,
 * Social, Creativity) are kept. So the rule is: Skill_All_Visible AND NOT
 * Skill_Toddler. Ids are confirmed from filenames (instance hex = skill id).
 *
 * Run: npx tsx scripts/diagnostics/buildSkillCriteriaIds.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';

const DIR = `${process.env.HOME}/Documents/Skill`;
const OUT = 'src/data/skillCriteriaIds.ts';

const ids: string[] = [];
for (const f of readdirSync(DIR)) {
  if (!f.endsWith('.StatisticTuning.xml')) continue;
  const m = f.match(/^[0-9A-F]+![0-9A-F]+!0*([0-9A-F]+)\./i);
  if (!m) continue;
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  if (!/<E>Skill_All_Visible<\/E>/.test(xml)) continue;  // game's visibility flag
  if (/<E>Skill_Toddler<\/E>/.test(xml)) continue;        // toddler skills excluded
  ids.push(parseInt(m[1], 16).toString(16));              // normalize: lowercase, no leading zeros
}
ids.sort((a, b) => parseInt(a, 16) - parseInt(b, 16));

const rows: string[] = [];
for (let i = 0; i < ids.length; i += 8) rows.push('  ' + ids.slice(i, i + 8).map((x) => `'${x}'`).join(', ') + ',');

const file = `/**
 * Skill tuning ids offered by the in-game criteria pickers (club membership /
 * small-business customer requirements). Generated by
 * scripts/diagnostics/buildSkillCriteriaIds.ts from the ~/Documents/Skill dump:
 * skills tagged Skill_All_Visible (the game's visibility flag) minus toddler
 * skills (Skill_Toddler). Excludes hidden/retail/non-skill statistics (Sales,
 * Maintenance, Work Ethic, Juice Pong, …) and toddler skills (Potty,
 * Communication, …); keeps child skills (Mental, Motor, Social, Creativity).
 * Ids are hex without 0x, lowercase, no leading zeros (matches skillIcons.ts).
 * DO NOT EDIT BY HAND.
 */
export const SKILL_CRITERIA_IDS = new Set<string>([
${rows.join('\n')}
]);
`;
writeFileSync(OUT, file);
console.log(`Wrote ${OUT} with ${ids.length} criteria-eligible skill ids.`);
