/**
 * Build src/data/stockActivities.ts — the shared "club interaction group" activity
 * catalog used by clubs, custom venues/getaways, and small businesses.
 *
 * Source: the EP/base ClubInteractionGroupTuning dump (type FA0FFA34) at
 * ~/Documents/Custom Venue/Club Interaction. Each record carries a display name,
 * a category, an icon resource key, and CONTEXT FLAGS that say which systems may
 * use it: custom_schedule_enabled (venues/getaways) and small_business_employee_rule
 * (Businesses & Hobbies). Every record is a club interaction group, so club=true.
 *
 * The tuning `s=` decimal == the resource instance, and that's the value the save
 * references, so we key the catalog by that decimal id (as a string).
 *
 * Run: npx tsx scripts/diagnostics/buildStockActivities.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';

const DUMP = `${process.env.HOME}/Documents/Custom Venue/Club Interaction`;
const OUT = 'src/data/stockActivities.ts';

interface Activity {
  id: string;            // decimal tuning id (== instance), what the save references
  key: string;           // clubInteractionGroup_* tuning name
  name: string;          // display name
  category: string | null;
  iconKey: string | null;   // category_icon resource key (type:group:instance)
  iconName: string | null;  // icon basename, e.g. clubs_rules_BeFriendly
  club: boolean;
  venue: boolean;        // custom_schedule_enabled
  smallBiz: boolean;     // small_business_employee_rule
}

function prettifyFromKey(key: string): string {
  // clubInteractionGroup_Social_BeFriendly -> "Social Be Friendly"
  const tail = key.replace(/^[Cc]lubInteractionGroup_/, '');
  return tail.replace(/_/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').trim();
}

const files = readdirSync(DUMP).filter((f) => f.endsWith('.ClubInteractionGroupTuning.xml'));
const out: Activity[] = [];

for (const f of files) {
  const xml = readFileSync(`${DUMP}/${f}`, 'utf8');
  const key = xml.match(/<I[^>]*\bn="([Cc]lubInteractionGroup_[^"]+)"/)?.[1];
  const id = xml.match(/<I[^>]*\bs="(\d+)"/)?.[1];
  if (!key || !id) continue;

  const nameM = xml.match(/<T n="name">0x[0-9A-Fa-f]+<!--(.*?)-->/);
  const name = nameM?.[1]?.trim() || prettifyFromKey(key);

  const category = xml.match(/<E n="category">([A-Z_]+)<\/E>/)?.[1] ?? null;

  const iconM = xml.match(/<T n="category_icon"[^>]*\bp="([^"]+)"[^>]*>([0-9a-fA-F:]+)<\/T>/);
  const iconPath = iconM?.[1] ?? null;
  const iconKey = iconM?.[2] ?? null;
  const iconName = iconPath ? iconPath.split(/[\\/]/).pop()!.replace(/\.png$/i, '') : null;

  const venue = /<V n="custom_schedule_enabled" t="enabled">/.test(xml);
  const smallBiz = /<T n="small_business_employee_rule">True/.test(xml);

  out.push({ id, key, name, category, iconKey, iconName, club: true, venue, smallBiz });
}

out.sort((a, b) => (a.category ?? '').localeCompare(b.category ?? '') || a.name.localeCompare(b.name));

const lines = out.map((a) =>
  `  '${a.id}': { key: '${a.key}', name: ${JSON.stringify(a.name)}, category: ${a.category ? `'${a.category}'` : 'null'}, ` +
  `icon: ${a.iconName ? `'${a.iconName}'` : 'null'}, iconKey: ${a.iconKey ? `'${a.iconKey}'` : 'null'}, ` +
  `club: ${a.club}, venue: ${a.venue}, smallBiz: ${a.smallBiz} },`
).join('\n');

const venueCount = out.filter((a) => a.venue).length;
const bizCount = out.filter((a) => a.smallBiz).length;

const file = `/**
 * Club interaction group activity catalog — SHARED by clubs, custom venues/getaways,
 * and small businesses. Generated by scripts/diagnostics/buildStockActivities.ts from
 * the ClubInteractionGroupTuning dump. DO NOT EDIT BY HAND.
 *
 * Keyed by the decimal tuning id (== resource instance) that the save references.
 * Context flags: club (always true), venue (custom_schedule_enabled, ${venueCount}),
 * smallBiz (small_business_employee_rule, ${bizCount}). icon = basename of the
 * category_icon png (not yet extracted); iconKey = its resource key for extraction.
 */
export interface StockActivity {
  key: string;
  name: string;
  category: string | null;
  icon: string | null;
  iconKey: string | null;
  club: boolean;
  venue: boolean;
  smallBiz: boolean;
}

export const STOCK_ACTIVITIES: Record<string, StockActivity> = {
${lines}
};

export type ActivityContext = 'club' | 'venue' | 'smallBiz';

/** Activities valid in a given system, sorted by category then name. */
export function activitiesFor(context: ActivityContext): Array<StockActivity & { id: string }> {
  return Object.entries(STOCK_ACTIVITIES)
    .filter(([, a]) => a[context])
    .map(([id, a]) => ({ id, ...a }));
}
`;

writeFileSync(OUT, file);
console.log(`wrote ${OUT}: ${out.length} activities (${venueCount} venue, ${bizCount} smallBiz, ${out.length} club)`);
const cats = [...new Set(out.map((a) => a.category))].filter(Boolean).sort();
console.log(`categories: ${cats.join(', ')}`);
console.log(`no category: ${out.filter((a) => !a.category).length}`);
