/* Generate src/data/stockHolidayDefaults.ts from the HolidayDefinitionTuning
 * export. Three maps:
 *   HOLIDAY_DECORATION_NAMES  decoration_preset id (decimal str) -> display name
 *   STOCK_HOLIDAY_TIME_OFF    holiday_type hex -> { work, school } default
 *   STOCK_HOLIDAY_DECORATION  holiday_type hex -> decoration_preset id (decimal str)
 * The save only stores a Holiday record (with f4 time_off_work / f5
 * time_off_school / f7 decoration_preset) when the player MODIFIED a holiday;
 * for stock holidays these tuning defaults are the effective values.
 * Run: npx tsx scripts/diagnostics/buildStockHolidayDefaults.ts */
import { readFileSync, readdirSync, writeFileSync } from 'fs';

const DIR = `${process.env.HOME}/Documents/Holiday`;
const files = readdirSync(DIR).filter((f) => f.endsWith('.HolidayDefinitionTuning.xml'));

// Clean a decoration codename -> display name: lotDecorationPresets_Holidays_LoveDay -> "Love Day"
const NAME_OVERRIDE: Record<string, string> = { HarvestFest: 'Harvestfest', NewYears: "New Year's", WinterFest: 'Winterfest', LoveDay: 'Love Day' };
function prettyDecoration(codeName: string): string {
  const tail = codeName.replace(/^lotDecorationPresets_Holidays_/, '');
  return NAME_OVERRIDE[tail] ?? tail.replace(/([a-z])([A-Z])/g, '$1 $2');
}

// Themes whose tunings aren't in the export, confirmed by save-diff (user seeding
// 2026-06-23: set on Hot Dog Day, diffed the record's f7). Extend as more surface.
const SAVE_CONFIRMED_DECORATIONS: Record<string, string> = {
  '191123': 'Spring',
  '191127': 'Spooky',
};

const decoNames: Record<string, string> = { ...SAVE_CONFIRMED_DECORATIONS };
const timeOff: Record<string, { work: boolean; school: boolean }> = {};
const decoration: Record<string, string> = {};

for (const f of files) {
  const m = f.match(/!0*([0-9A-Fa-f]+)\.([^.]+)\.HolidayDefinitionTuning\.xml$/);
  if (!m) continue;
  const id = m[1].toLowerCase();
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  const work = /<T n="time_off_work">\s*True/i.test(xml);
  const school = /<T n="time_off_school">\s*True/i.test(xml);
  if (work || school) timeOff[id] = { work, school };
  const dec = xml.match(/<V n="decoration_preset"[\s\S]*?<T n="enabled">\s*(\d+)<!--([^>]*?)-->/);
  if (dec) {
    const presetId = dec[1];
    decoration[id] = presetId;
    if (!decoNames[presetId]) decoNames[presetId] = prettyDecoration(dec[2].trim());
  }
}

const sortRec = (r: Record<string, unknown>) => Object.fromEntries(Object.entries(r).sort((a, b) => a[0].localeCompare(b[0])));
const out = `/**
 * Stock holiday DEFAULTS (time off + decoration theme), generated by
 * scripts/diagnostics/buildStockHolidayDefaults.ts from HolidayDefinitionTuning.
 * Used for holidays the player hasn't customized (the save only stores a record
 * — with f4 time_off_work / f5 time_off_school / f7 decoration_preset — when
 * modified). DO NOT EDIT BY HAND.
 */

/** Decoration-preset id (decimal string, as stored in the holiday record's f7) -> display name. */
export const HOLIDAY_DECORATION_NAMES: Record<string, string> = ${JSON.stringify(sortRec(decoNames), null, 2)};

/** Resolve a decoration-preset id to its theme name, or null when none/unknown. */
export function holidayDecorationName(presetId: string | null): string | null {
  if (!presetId || presetId === '0') return null;
  return HOLIDAY_DECORATION_NAMES[presetId] ?? \`Theme #\${presetId}\`;
}

/** holiday_type hex -> default day-off (work/school) for stock holidays. */
export const STOCK_HOLIDAY_TIME_OFF: Record<string, { work: boolean; school: boolean }> = ${JSON.stringify(sortRec(timeOff), null, 2)};

/** holiday_type hex -> default decoration-preset id (decimal string) for stock holidays. */
export const STOCK_HOLIDAY_DECORATION: Record<string, string> = ${JSON.stringify(sortRec(decoration), null, 2)};
`;
writeFileSync('src/data/stockHolidayDefaults.ts', out);
console.log(`decoration names: ${Object.keys(decoNames).length}`, decoNames);
console.log(`time-off defaults: ${Object.keys(timeOff).length}, decoration defaults: ${Object.keys(decoration).length}`);
console.log('wrote src/data/stockHolidayDefaults.ts');
