/* Generate src/data/stockHolidays.ts — the holidays EA puts ON THE CALENDAR,
 * with their display name and icon, read from the HolidayDefinitionTuning files.
 * The save stores a Holiday record (carrying a name + icon) only for a holiday
 * the player has EDITED, so an untouched stock holiday reaches us as a bare
 * calendar placement and its name has to come from here.
 *
 * Both fields are literal in the tuning, no string table needed:
 *   <V n="instance_display_name"><T n="enabled">0xCA32BDC9<!--The Lottery--></T>
 *   <V n="instance_display_icon"><T n="enabled" p="...">TYPE:GROUP:INSTANCE</T>
 * The icon's INSTANCE is the filename in public/holiday-icons/, so it maps with
 * no lookup table.
 *
 * SURPRISE HOLIDAYS ARE EXCLUDED. The eight premadeHolidays_Surprise_* tunings
 * (The Lottery, Prank Day, Talk Like a Pirate Day…) are fired as drama-node
 * events, not written into the save's calendar as placements — no holiday of
 * those types appears in any of the 56 saves in the dev database, while the four
 * calendar holidays appear in every one. Their names and icons are perfectly
 * readable here, but a mapping nothing can reach is a guess about the save
 * format wearing a generated file's clothes. If one ever turns up in a real
 * calendar, delete the filter below and re-run.
 *
 * Run: npx tsx scripts/diagnostics/buildStockHolidays.ts */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'fs';

const DIR = `${process.env.HOME}/Documents/Holiday`;
const ICON_DIR = 'public/holiday-icons';

const files = readdirSync(DIR).filter((f) => f.endsWith('.HolidayDefinitionTuning.xml')).sort();
const shipped = new Set(readdirSync(ICON_DIR).map((f) => f.replace(/\.png$/, '')));

type Entry = { id: string; tuningName: string; name: string; icon: string };
const kept: Entry[] = [];

for (const f of files) {
  const m = f.match(/!0*([0-9A-Fa-f]+)\.([^.]+)\.HolidayDefinitionTuning\.xml$/);
  if (!m) continue;
  if (m[2].includes('_Surprise_')) { console.log(`  skipped (event, never on the calendar): ${m[2]}`); continue; }
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  const name = xml.match(/instance_display_name[\s\S]*?<!--(.*?)-->/)?.[1];
  const key = xml.match(/instance_display_icon[\s\S]*?<T n="enabled"[^>]*>([0-9a-f:]+)</)?.[1];
  const icon = key?.split(':')[2] ?? '';
  // No name means nothing to resolve — skip rather than invent one.
  if (!name) { console.warn(`  skipped (no display name): ${m[2]}`); continue; }
  if (icon && !shipped.has(icon)) console.warn(`  icon not in ${ICON_DIR}: ${name} (${icon})`);
  kept.push({ id: m[1].toLowerCase(), tuningName: m[2], name, icon });
}
kept.sort((a, b) => parseInt(a.id, 16) - parseInt(b.id, 16));

const pad = Math.max(...kept.map((e) => e.name.length)) + 3;
const body = kept
  .map((e) => `  '${e.id}': { name: ${`${JSON.stringify(e.name)},`.padEnd(pad)} icon: '${e.icon}' },`)
  .join('\n');

writeFileSync('src/data/stockHolidays.ts', `// The holidays EA puts on the calendar, keyed by holiday_type (the save's
// Holiday tuning ID) as lowercase hex without the 0x prefix. Generated by
// scripts/diagnostics/buildStockHolidays.ts from the HolidayDefinitionTuning
// files. DO NOT EDIT BY HAND.
//
// The save stores a Holiday record only for a holiday the player has edited, so
// an untouched stock holiday arrives as a bare calendar placement and takes its
// name and icon from here. A save that DOES carry a name overrides this map —
// including a localised one, so a French save's Winterfest reads Noël.
//
// EA's eight SURPRISE holidays are deliberately absent: they fire as events and
// are never written into the save's calendar. See the generator's header.
//
// \`icon\` is the icon ResourceKey's instance hex, which is also its filename in
// public/holiday-icons/.

export interface StockHoliday {
  name: string;
  icon: string;
}

export const STOCK_HOLIDAYS: Record<string, StockHoliday> = {
${body}
};

export function resolveStockHoliday(holidayType: bigint): StockHoliday | null {
  return STOCK_HOLIDAYS[holidayType.toString(16).toLowerCase()] ?? null;
}
`);
console.log(`wrote src/data/stockHolidays.ts (${kept.length} holidays)`);
