/**
 * Build src/data/premadeAncestors.ts from the extracted TunablePremadeAncestor
 * tuning XMLs (`~/Documents/family/`). Each deceased premade ancestor in the
 * modern family tree is a template referenced by id from the save's genealogy
 * structure; this catalog turns that id into a name / gender / death / portrait.
 *
 * Run: npx tsx scripts/diagnostics/buildPremadeAncestors.ts
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { homedir } from 'os';

const DIR = `${homedir()}/Documents/family`;
const OUT = `${process.cwd()}/src/data/premadeAncestors.ts`;

interface Ancestor { name: string; gender: 'male' | 'female'; deathCause?: string; title?: string; thumbnail?: string; }
const catalog: Record<string, Ancestor> = {};

const comment = (xml: string, field: string): string | null => {
  // First comment INSIDE the <V n="field">…</V> block (null if the field is
  // absent — never fall back to the whole file, or an absent field steals
  // another field's comment, e.g. title picking up the death-trait).
  const block = new RegExp(`<V n="${field}"[^>]*>([\\s\\S]*?)</V>`).exec(xml);
  if (!block) return null;
  const m = /<!--([^>]*?)-->/.exec(block[1]);
  return m ? m[1].trim() : null;
};

let count = 0;
for (const f of readdirSync(DIR)) {
  if (!/Ancestor.*\.SimTemplateTuning\.xml$/i.test(f)) continue;
  const xml = readFileSync(`${DIR}/${f}`, 'utf8');
  if (!/c="TunablePremadeAncestor"/.test(xml)) continue;
  // instance id from filename: TYPE!GROUP!INSTANCE.name.xml
  const idHex = f.split('!')[2]?.split('.')[0];
  if (!idHex) continue;
  const key = '0x' + BigInt('0x' + idHex).toString(16);

  const name = comment(xml, 'full_name');
  if (!name) continue;
  const a: Ancestor = { name, gender: 'male' };
  // ABSENT MEANS MALE. The tuning writes <E n="gender"> only for women and for
  // the EP21 ancestors whose authors wrote it anyway; 13 of the 41 base-game
  // templates leave it out entirely — Sef Darong, Simon Crumplebottom, Ade
  // Darong (titled Grand Duke), Cahya Bapak (bapak = father, paired with Wulan
  // Ibu who IS marked FEMALE), and so on. Owner-confirmed in game. Reading an
  // absent field as female made them women on screen, complete with a Mother /
  // Grandmother chip, and pulled tree-only ancestors down to 10% male against a
  // 47% roster. Always emit a gender so no consumer has to invent one.
  const g = /<E n="gender">(\w+)<\/E>/.exec(xml);
  a.gender = g && g[1] === 'FEMALE' ? 'female' : 'male';
  const death = comment(xml, 'death_trait');             // trait_ghost_OldAge -> OldAge
  if (death) a.deathCause = death.replace(/^trait_ghost_/, '');
  const title = comment(xml, 'kingdom_data');            // localized_title comment (first), e.g. Grand Duchess
  if (title && title !== name) a.title = title;
  const thumb = /<V n="thumbnail"[\s\S]*?<T[^>]*>([0-9a-f]{8}:[0-9a-f]{8}:[0-9a-f]{16})</i.exec(xml);
  if (thumb) a.thumbnail = thumb[1];
  catalog[key] = a;
  count++;
}

const entries = Object.entries(catalog).sort((a, b) => a[0].localeCompare(b[0]));
const body = entries.map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`).join('\n');
const out = `/**
 * Premade deceased-ancestor catalog for the modern (Feb-2026 patch) family
 * tree. Keyed by the ancestor's TunablePremadeAncestor template instance id
 * (hex), as referenced from a save's genealogy structure via the
 * ancestor-node->template map (see src/lib/parser/genealogy.ts).
 *
 * GENERATED by scripts/diagnostics/buildPremadeAncestors.ts from extracted
 * tuning — do not edit by hand. Covers ${count} ancestors; expand by extracting
 * more TunablePremadeAncestor tunings if ancestor nodes render unnamed.
 */
export interface PremadeAncestor {
  name: string;
  /** Always set. The tuning states gender only for women (and for the EP21
   *  ancestors, whose authors wrote it either way); an absent field means male,
   *  confirmed in game. Never make this optional again — a missing gender is
   *  what turned thirteen dead men into great-grandmothers. */
  gender: 'male' | 'female';
  /** Death-cause token (e.g. 'OldAge', 'Fire'), from the ghost-trait taxonomy. */
  deathCause?: string;
  /** Royal/localized title where the ancestor has one (e.g. 'Grand Duchess'). */
  title?: string;
  /** Portrait ResourceKey (type:group:instance) for the in-game ancestor icon. */
  thumbnail?: string;
}

export const PREMADE_ANCESTORS: Record<string, PremadeAncestor> = {
${body}
};
`;
writeFileSync(OUT, out);
console.log(`Wrote ${count} premade ancestors -> ${OUT}`);
