#!/usr/bin/env node
/**
 * Concatenate docs/product-facts/ into one file you can paste into a Claude
 * project (or hand to a person) in a single go.
 *
 *   npm run product-facts
 *
 * Order is deliberate: the rules first, then the two files that constrain every
 * claim, then the surfaces alphabetically. Someone reading top-to-bottom meets
 * "here's what you must never say" before they meet the material they'd say it
 * about.
 *
 * The output is generated and gitignored — `PRODUCT_FACTS.md` has been in
 * .gitignore since the original root-level one. The SOURCE is what's tracked;
 * this is a convenience build of it, so never hand-edit the result.
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const DIR = path.join(process.cwd(), 'docs', 'product-facts');
const OUT = path.join(DIR, 'PRODUCT_FACTS.md');
const LEAD = ['README.md', '00-core-model.md', 'do-not-claim.md', 'glossary.md'];

if (!fs.existsSync(DIR)) {
  console.error(`No ${path.relative(process.cwd(), DIR)} — run this from the repo root.`);
  process.exit(1);
}

const surfaceDir = path.join(DIR, 'surfaces');
const surfaces = fs.existsSync(surfaceDir)
  ? fs.readdirSync(surfaceDir).filter((f) => f.endsWith('.md')).sort()
  : [];

const parts = [];
const included = [];

for (const name of LEAD) {
  const file = path.join(DIR, name);
  if (!fs.existsSync(file)) continue;      // 00-core-model is deliberately absent
  parts.push(fs.readFileSync(file, 'utf8').trim());
  included.push(name);
}

for (const name of surfaces) {
  parts.push(fs.readFileSync(path.join(surfaceDir, name), 'utf8').trim());
  included.push(`surfaces/${name}`);
}

// Stamp the build so feedback can be traced to a version. Someone reads this
// file for a week, sends notes back, and the first question is always "which
// copy were you looking at?" — the commit answers it exactly.
let stamp = 'unknown revision';
try {
  const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: process.cwd(), encoding: 'utf8' }).trim();
  const when = execFileSync('git', ['log', '-1', '--format=%cs'], { cwd: process.cwd(), encoding: 'utf8' }).trim();
  stamp = `${sha} · ${when}`;
} catch { /* not a git checkout — the rest still builds */ }

const header = [
  '# MySaveFile — product facts',
  '',
  `**Version ${stamp}.** Quote this when sending feedback — it says exactly which`,
  'copy you read, and these files change.',
  '',
  'Generated by `npm run product-facts` from `docs/product-facts/`.',
  'Do not edit this file: edit the source and re-run.',
  '',
  `${surfaces.length} surfaces, ${included.length} files in total.`,
].join('\n');

fs.writeFileSync(OUT, `${header}\n\n---\n\n${parts.join('\n\n---\n\n')}\n`);

const kb = Math.round(fs.statSync(OUT).size / 1024);
console.log(`${path.relative(process.cwd(), OUT)} — ${included.length} files, ${kb} KB`);
for (const name of included) console.log(`  ${name}`);
