/**
 * Premade deceased-ancestor catalog for the modern (Feb-2026 patch) family
 * tree. Keyed by the ancestor's TunablePremadeAncestor template instance id
 * (hex), as referenced from a save's genealogy structure via the
 * ancestor-node->template map (see src/lib/parser/genealogy.ts).
 *
 * GENERATED by scripts/diagnostics/buildPremadeAncestors.ts from extracted
 * tuning — do not edit by hand. Covers 41 ancestors; expand by extracting
 * more TunablePremadeAncestor tunings if ancestor nodes render unnamed.
 */
export interface PremadeAncestor {
  name: string;
  /** Always set. The tuning states gender only for women (and for the EP21
   *  ancestors, whose authors wrote it either way); an absent field means male,
   *  confirmed in game. Never make this optional again — a missing gender is
   *  what turned thirteen dead men into great-grandmothers. */
  gender: 'male' | 'female';
  /** Death-cause token (e.g. 'OldAge', 'Fire'), from the ghost-trait taxonomy. */
  deathCause?: string;
  /** Royal/localized title where the ancestor has one (e.g. 'Grand Duchess'). */
  title?: string;
  /** Portrait ResourceKey (type:group:instance) for the in-game ancestor icon. */
  thumbnail?: string;
}

export const PREMADE_ANCESTORS: Record<string, PremadeAncestor> = {
  '0x78166': {"name":"Aghata Ananou","gender":"female","deathCause":"Fire","thumbnail":"2f7d0004:00000000:0310dd5c4b390b25"},
  '0x7861b': {"name":"Cordelia Thebe II","gender":"female","deathCause":"Drown","title":"Grand Duchess","thumbnail":"2f7d0004:00000000:013c0e7d51f95bf4"},
  '0x7861c': {"name":"Cordelia Thebe III","gender":"female","deathCause":"Fire","title":"Marchioness","thumbnail":"2f7d0004:00000000:126892f24ab73ff5"},
  '0x7861d': {"name":"Cordelia Thebe IV","gender":"female","deathCause":"Drown","title":"Grand Duchess","thumbnail":"2f7d0004:00000000:013c0e7d51f95beb"},
  '0x78630': {"name":"Queen Thebe","gender":"female","deathCause":"Drown","title":"Queen","thumbnail":"2f7d0004:00000000:9dae9e4b2dc15c21"},
  '0x78631': {"name":"John Wilson Beard Beard","gender":"male","deathCause":"trait_Ghost_Meteorite","thumbnail":"2f7d0004:00000000:e2bbc07ed0ecd79c"},
  '0x786e5': {"name":"Eetion Thebe","gender":"male","deathCause":"OldAge","title":"Duke","thumbnail":"2f7d0004:00000000:a50068e582a02ec7"},
  '0x786e6': {"name":"Cordelia Capp","gender":"female","deathCause":"Fire","title":"Grand Duchess","thumbnail":"2f7d0004:00000000:bea7a2fb95f4185c"},
  '0x786e7': {"name":"Andromache Thebe","gender":"female","deathCause":"Electrocution","title":"Grand Duchess","thumbnail":"2f7d0004:00000000:cdd607446e396e47"},
  '0x786e8': {"name":"Hector Thebe","gender":"male","deathCause":"Cowplant","thumbnail":"2f7d0004:00000000:19a8b67e903299e0"},
  '0x786e9': {"name":"Contessa Capp","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:140529760af05171"},
  '0x786ea': {"name":"Caliban Capp","gender":"male","deathCause":"Fire","thumbnail":"2f7d0004:00000000:4e973b548dcc0f7f"},
  '0x78784': {"name":"Lina Darong","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:f3b4841cffa86356"},
  '0x78785': {"name":"Sef Darong","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:37f1aa205a3f24d8"},
  '0x78786': {"name":"Delilah Dreamer","gender":"female","deathCause":"Electrocution","thumbnail":"2f7d0004:00000000:0e2fd52ac69ead84"},
  '0x78787': {"name":"Davis Dreamer","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:d5f075b82e6f12c6"},
  '0x78788': {"name":"Darren Dreamer","gender":"male","deathCause":"trait_Ghost_BrokenHeart","thumbnail":"2f7d0004:00000000:20b6e4285759885b"},
  '0x78789': {"name":"Darleen Dreamer","gender":"female","deathCause":"Fire","thumbnail":"2f7d0004:00000000:952fb5204172b496"},
  '0x787c2': {"name":"Ade Darong","gender":"male","deathCause":"OldAge","title":"Grand Duke","thumbnail":"2f7d0004:00000000:23062ba9ddea588a"},
  '0x787c3': {"name":"Eniola Darong","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:2b7b046023ba83a4"},
  '0x787c4': {"name":"Imani Darong","gender":"female","deathCause":"trait_Ghost_SecretPassageway","thumbnail":"2f7d0004:00000000:79f08b068b6333d2"},
  '0x787c5': {"name":"Unknown","gender":"female"},
  '0x78814': {"name":"Bert Alto","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:71dc523858c187dc"},
  '0x78815': {"name":"Nick Alto","gender":"male","deathCause":"Fire","thumbnail":"2f7d0004:00000000:4412d8192817dd08"},
  '0x78816': {"name":"Vita Alto","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:5ff290e18229d063"},
  '0x78817': {"name":"Unknown","gender":"female"},
  '0x788b6': {"name":"Rodrigo De Pablo","gender":"male","deathCause":"Fire","thumbnail":"2f7d0004:00000000:7ff9fcbcc428f226"},
  '0x788b7': {"name":"Rodrigo Thebe","gender":"male","deathCause":"Drown","thumbnail":"2f7d0004:00000000:987b1f2b3a8877b5"},
  '0x788b8': {"name":"Unknown","gender":"male"},
  '0x791a5': {"name":"Wulan Ibu","gender":"female","deathCause":"Electrocution","thumbnail":"2f7d0004:00000000:f32cd1e2f3319154"},
  '0x791a6': {"name":"Cahya Bapak","gender":"male","deathCause":"Electrocution","thumbnail":"2f7d0004:00000000:e94b2a799f87b81e"},
  '0x791a7': {"name":"Cornelia Goth","gender":"female","deathCause":"Fire","thumbnail":"2f7d0004:00000000:94e1f2f39a10fec4"},
  '0x791ce': {"name":"Prudence Crumplebottom","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:66fc80b8384ecdf0"},
  '0x791cf': {"name":"Simon Crumplebottom","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:2585706ebbbb2ef4"},
  '0x7a97d': {"name":"Gioia Vatore","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:292113f8e9e5bb75"},
  '0x7a986': {"name":"Vittorio Pasquale","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:f831b60aeda8bcef"},
  '0x7a991': {"name":"Fiorenza Zhu","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:37044b79a3924136"},
  '0x7a99b': {"name":"Manu Kealoha","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:43dc44bd178dd9fb"},
  '0x7a9a5': {"name":"Tallulah Grove","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:cefd52fd4de4b4a5"},
  '0x7a9a7': {"name":"Orodueynna Gomes","gender":"female","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:69748b53b81e02b6"},
  '0x7a9a9': {"name":"Pranav Kunal","gender":"male","deathCause":"OldAge","thumbnail":"2f7d0004:00000000:984b20a69af5cbb8"},
};
