/**
 * Skill tuning ids offered by the in-game criteria pickers (club membership /
 * small-business customer requirements). Generated by
 * scripts/diagnostics/buildSkillCriteriaIds.ts from the ~/Documents/Skill dump:
 * skills tagged Skill_All_Visible (the game's visibility flag) minus toddler
 * skills (Skill_Toddler). Excludes hidden/retail/non-skill statistics (Sales,
 * Maintenance, Work Ethic, Juice Pong, …) and toddler skills (Potty,
 * Communication, …); keeps child skills (Mental, Motor, Social, Creativity).
 * Ids are hex without 0x, lowercase, no leading zeros (matches skillIcons.ts).
 * DO NOT EDIT BY HAND.
 */
export const SKILL_CRITERIA_IDS = new Set<string>([
  '4113', '4137', '413a', '413b', '413c', '413d', '413e', '413f',
  '4140', '4141', '4142', '4143', '4144', '4145', '4146', '4148',
  '4149', '414a', '414e', '414f', '4150', '4151', '99e5', '18e20',
  '19706', '19d2e', '1cc62', '1db0c', '1f491', '21a53', '24834', '248a1',
  '26bc3', '272f8', '275a6', '275c4', '2a89d', '2aa5f', '2d94f', '2f08f',
  '2f8a7', '35145', '35f56', '389e4', '39536', '3a7a1', '3bf6d', '3bf87',
  '3c126', '3e511', '3f6ae', '42f15', '4d171', '4ec94', '4f417', '4f418',
  '4f419', '4f41a', '55afc', '5a02c', '5a9b9', '5ab19', '5ce4f', '6a2dd',
  '6b3b6', '6dea6', '6e5e3', '6eeb8', '6fff6', '72b9b',
]);
