/**
 * Sims-Team (EA) premade venue presets — the built-in starter templates.
 * Generated by scripts/diagnostics/buildVenuePresets.py from the
 * ~/Documents/Custom Venue tuning snippets. DO NOT EDIT BY HAND.
 *
 * These are read-only stock templates (Layer 1), distinct from a player's own
 * imported/authored presets. data matches the parser's ParsedCustomVenue
 * (schedules) / ParsedVenueRole (roles) shapes so the display reuses them.
 */
import type { ParsedCustomVenue, ParsedVenueRole } from '../lib/parser/types';

export interface StockVenuePreset<T> { key: string; name: string; data: T }

export const STOCK_VENUE_PRESETS: {
  schedules: StockVenuePreset<ParsedCustomVenue>[];
  roles: StockVenuePreset<ParsedVenueRole>[];
} = {
  schedules: [
  {
    "key": "76b16",
    "name": "24 Hour Entertainment Center",
    "data": {
      "name": "24 Hour Entertainment Center",
      "lotId": null,
      "roles": [
        {
          "name": "Visitor",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "none"
          },
          "index": 0
        },
        {
          "name": "Comedian",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": false,
              "values": [
                16698
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "122434"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 1
        },
        {
          "name": "Gamer",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122439",
            "380467"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 2
        },
        {
          "name": "Chef",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": true,
              "values": [
                16701,
                16705,
                104198
              ],
              "rawType": 0
            },
            {
              "type": "fame",
              "required": false,
              "values": [
                3
              ],
              "rawType": 7
            }
          ],
          "activities": [
            "122480",
            "462612",
            "122422",
            "486117"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 3
        },
        {
          "name": "Staff",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122483"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 4
        },
        {
          "name": "Musician",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "category"
          },
          "index": 5
        },
        {
          "name": "Bartender",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": true,
              "values": [
                16695
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "401371",
            "122436"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 6
        },
        {
          "name": "DJ",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": false,
              "values": [
                121612
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "122547"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 7
        }
      ],
      "slots": [
        {
          "hour": 0,
          "mainActivity": "122479",
          "assignments": [
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 5,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 6,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 8,
          "mainActivity": "128541",
          "assignments": [
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 5,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 6,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 12,
          "mainActivity": "462655",
          "assignments": [
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 5,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 6,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 16,
          "mainActivity": "485232",
          "assignments": [
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 5,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 6,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "122434",
          "assignments": [
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 5,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 6,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "76b15",
    "name": "Bachelor / Bachelorette",
    "data": {
      "name": "Bachelor / Bachelorette",
      "lotId": null,
      "roles": [
        {
          "name": "Bachelorette",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                27454
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "462655"
          ],
          "outfit": {
            "mode": "none"
          },
          "index": 0
        },
        {
          "name": "Singles",
          "simCount": 8,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478655
              ],
              "rawType": 1
            },
            {
              "type": "relationship",
              "required": true,
              "values": [],
              "rawType": 13
            }
          ],
          "activities": [
            "462656"
          ],
          "outfit": {
            "mode": "none"
          },
          "index": 1
        }
      ],
      "slots": [
        {
          "hour": 7,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 10,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 13,
          "mainActivity": "462655",
          "assignments": [
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "122479",
          "assignments": [
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 23,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f335",
    "name": "Cooking Competition",
    "data": {
      "name": "Cooking Competition",
      "lotId": null,
      "roles": [
        {
          "name": "Amateur Chef",
          "simCount": 5,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                27176
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "122443",
            "126320"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 0
        },
        {
          "name": "Chef",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": true,
              "values": [
                16701,
                16705,
                104198
              ],
              "rawType": 0
            },
            {
              "type": "fame",
              "required": false,
              "values": [
                3
              ],
              "rawType": 7
            }
          ],
          "activities": [
            "122480",
            "462612",
            "122422",
            "486117"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 1
        },
        {
          "name": "Mean Chef",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": true,
              "values": [
                16701,
                16705,
                104198
              ],
              "rawType": 0
            },
            {
              "type": "fame",
              "required": false,
              "values": [
                3
              ],
              "rawType": 7
            }
          ],
          "activities": [
            "122480",
            "462612",
            "121698",
            "486117"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 2
        },
        {
          "name": "Staff",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122483"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 3
        }
      ],
      "slots": [
        {
          "hour": 7,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": ["122483"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 10,
          "mainActivity": "122443",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 16,
          "mainActivity": "462612",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": ["122483"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "462625",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 23,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f337",
    "name": "Cozy Bed and Breakfast",
    "data": {
      "name": "Cozy Bed and Breakfast",
      "lotId": null,
      "roles": [
        {
          "name": "Guest",
          "simCount": 6,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122422",
            "122484",
            "122480",
            "122469",
            "122479"
          ],
          "outfit": {
            "mode": "none"
          },
          "index": 0
        },
        {
          "name": "Host",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122483",
            "122422",
            "122443",
            "401371",
            "122445"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 1
        },
        {
          "name": "Staff",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122483"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 2
        }
      ],
      "slots": [
        {
          "hour": 7,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 10,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 23,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f345",
    "name": "Creativity Retreat",
    "data": {
      "name": "Creativity Retreat",
      "lotId": null,
      "roles": [
        {
          "name": "Writer",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": false,
              "values": [
                16714
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "122440"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 0
        },
        {
          "name": "Artist",
          "simCount": 4,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": true,
              "values": [
                16708,
                371129,
                450214
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "122472",
            "122433",
            "410875",
            "394921",
            "458335"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 1
        },
        {
          "name": "Musician",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "category"
          },
          "index": 2
        },
        {
          "name": "Staff",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122483"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 3
        }
      ],
      "slots": [
        {
          "hour": 7,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 10,
          "mainActivity": "458594",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "458594",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 23,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f333",
    "name": "Fitness Retreat",
    "data": {
      "name": "Fitness Retreat",
      "lotId": null,
      "roles": [
        {
          "name": "Retreat Guest",
          "simCount": 6,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478631
              ],
              "rawType": 1
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "category"
          },
          "index": 0
        },
        {
          "name": "Retreat Leader",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478652
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "122422",
            "122483",
            "122450",
            "486554"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 1
        },
        {
          "name": "Fitness Trainer",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478653
              ],
              "rawType": 1
            },
            {
              "type": "skill",
              "required": true,
              "values": [
                16659
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "122422",
            "122483",
            "121923",
            "486554"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 2
        }
      ],
      "slots": [
        {
          "hour": 0,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 7,
          "mainActivity": "121923",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462620"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["462621"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 10,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["475892"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 13,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["122476"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["121923"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 18,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 21,
          "mainActivity": "462625",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["122422"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["122422"],
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f332",
    "name": "Outdoor Kids Camp",
    "data": {
      "name": "Outdoor Kids Camp",
      "lotId": null,
      "roles": [
        {
          "name": "Camper",
          "simCount": 8,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                4
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478628
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "122422",
            "475758"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 0
        },
        {
          "name": "Camp Counselor",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                24
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478629
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "481435",
            "122483",
            "122422"
          ],
          "outfit": {
            "mode": "custom"
          },
          "index": 1
        },
        {
          "name": "Camp Director",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478630
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "122422",
            "481435"
          ],
          "outfit": {
            "mode": "none"
          },
          "index": 2
        }
      ],
      "slots": [
        {
          "hour": 6,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 9,
          "mainActivity": "462628",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["459526"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["481435"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["481435"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 13,
          "mainActivity": "462635",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122476"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["481435"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["481435"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462641",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["462641"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["481435"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["481435"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 22,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 2,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f334",
    "name": "Romantic Competition",
    "data": {
      "name": "Romantic Competition",
      "lotId": null,
      "roles": [
        {
          "name": "Singles",
          "simCount": 8,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478655
              ],
              "rawType": 1
            },
            {
              "type": "relationship",
              "required": true,
              "values": [],
              "rawType": 13
            }
          ],
          "activities": [
            "462656"
          ],
          "outfit": {
            "mode": "none"
          },
          "index": 0
        },
        {
          "name": "Romantic Host",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                478656
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "122422",
            "122483",
            "122450"
          ],
          "outfit": {
            "mode": "none"
          },
          "index": 1
        }
      ],
      "slots": [
        {
          "hour": 1,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 8,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 11,
          "mainActivity": "475758",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462644"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "462655",
          "assignments": [
            {
              "roleIndex": 0,
              "activityOverrides": ["122431"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["122431"],
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "76b14",
    "name": "Senior Living Community",
    "data": {
      "name": "Senior Living Community",
      "lotId": null,
      "roles": [
        {
          "name": "Senior",
          "simCount": 6,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                64
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "none"
          },
          "index": 0
        },
        {
          "name": "Visitor",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "none"
          },
          "index": 1
        },
        {
          "name": "Staff",
          "simCount": 2,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122483"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 2
        },
        {
          "name": "Entertainer",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": false,
              "values": [
                16698,
                16702,
                16709,
                16713,
                149665,
                121612,
                137811
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "485232",
            "149981",
            "122434",
            "122479"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 3
        }
      ],
      "slots": [
        {
          "hour": 5,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 8,
          "mainActivity": "121923",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 11,
          "mainActivity": "380467",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 16,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": ["462612"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 19,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 22,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "76b13",
    "name": "Sim Popularity Contest",
    "data": {
      "name": "Sim Popularity Contest",
      "lotId": null,
      "roles": [
        {
          "name": "Sporty Sim",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "128505",
            "121923"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 0
        },
        {
          "name": "Brainy Sim",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "458594",
            "122439"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 1
        },
        {
          "name": "Friendly Sim",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "122422"
          ],
          "outfit": {
            "mode": "category"
          },
          "index": 2
        },
        {
          "name": "Rebel Sim",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            }
          ],
          "activities": [
            "485235"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 3
        },
        {
          "name": "Popular Sim",
          "simCount": 3,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                112
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "style"
          },
          "index": 4
        }
      ],
      "slots": [
        {
          "hour": 7,
          "mainActivity": "462615",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 4,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 10,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 13,
          "mainActivity": "475758",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462618",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 4,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": ["122480"],
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 20,
          "mainActivity": "475613",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 4,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 23,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 4,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": ["483838"],
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  },
  {
    "key": "6f336",
    "name": "Wilderness Park",
    "data": {
      "name": "Wilderness Park",
      "lotId": null,
      "roles": [
        {
          "name": "Outdoor Enthusiast",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": false,
              "values": [
                27914
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "462634",
            "462635"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 0
        },
        {
          "name": "Fishermen",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "skill",
              "required": false,
              "values": [
                39397
              ],
              "rawType": 0
            }
          ],
          "activities": [
            "122444"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 1
        },
        {
          "name": "Park Ranger",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            }
          ],
          "activities": [],
          "outfit": {
            "mode": "style"
          },
          "index": 2
        },
        {
          "name": "Outdoor Collector",
          "simCount": 1,
          "criteria": [
            {
              "type": "age",
              "required": true,
              "values": [
                120
              ],
              "rawType": 5
            },
            {
              "type": "trait",
              "required": true,
              "values": [
                27914
              ],
              "rawType": 1
            }
          ],
          "activities": [
            "462644",
            "129789"
          ],
          "outfit": {
            "mode": "style"
          },
          "index": 3
        }
      ],
      "slots": [
        {
          "hour": 6,
          "mainActivity": "475758",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 17,
          "mainActivity": "462641",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        },
        {
          "hour": 22,
          "mainActivity": "483838",
          "assignments": [
            {
              "roleIndex": 2,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 0,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 1,
              "activityOverrides": null,
              "outfitOverride": null
            },
            {
              "roleIndex": 3,
              "activityOverrides": null,
              "outfitOverride": null
            }
          ]
        }
      ]
    }
  }
],
  roles: [
  {
    "key": "76b06",
    "name": "Amateur Chef",
    "data": {
      "name": "Amateur Chef",
      "simCount": 5,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            27176
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "122443",
        "126320"
      ],
      "outfit": {
        "mode": "custom"
      },
      "index": 0
    }
  },
  {
    "key": "6f365",
    "name": "Artist",
    "data": {
      "name": "Artist",
      "simCount": 4,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": true,
          "values": [
            16708,
            371129,
            450214
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "122472",
        "122433",
        "410875",
        "394921",
        "458335"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "76b12",
    "name": "Bachelorette",
    "data": {
      "name": "Bachelorette",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            27454
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "462655"
      ],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "6f368",
    "name": "Bartender",
    "data": {
      "name": "Bartender",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": true,
          "values": [
            16695
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "401371",
        "122436"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b0b",
    "name": "Brainy Sim",
    "data": {
      "name": "Brainy Sim",
      "simCount": 3,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "458594",
        "122439"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "6f34c",
    "name": "Camp Counselor",
    "data": {
      "name": "Camp Counselor",
      "simCount": 2,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            24
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478629
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "481435",
        "122483",
        "122422"
      ],
      "outfit": {
        "mode": "custom"
      },
      "index": 0
    }
  },
  {
    "key": "6f34b",
    "name": "Camp Director",
    "data": {
      "name": "Camp Director",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478630
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "122422",
        "481435"
      ],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "6f34a",
    "name": "Camper",
    "data": {
      "name": "Camper",
      "simCount": 8,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            4
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478628
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "122422",
        "475758"
      ],
      "outfit": {
        "mode": "custom"
      },
      "index": 0
    }
  },
  {
    "key": "6f369",
    "name": "Chef",
    "data": {
      "name": "Chef",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": true,
          "values": [
            16701,
            16705,
            104198
          ],
          "rawType": 0
        },
        {
          "type": "fame",
          "required": false,
          "values": [
            3
          ],
          "rawType": 7
        }
      ],
      "activities": [
        "122480",
        "462612",
        "122422",
        "486117"
      ],
      "outfit": {
        "mode": "custom"
      },
      "index": 0
    }
  },
  {
    "key": "6f363",
    "name": "Child",
    "data": {
      "name": "Child",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            4
          ],
          "rawType": 5
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "76b18",
    "name": "Comedian",
    "data": {
      "name": "Comedian",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": false,
          "values": [
            16698
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "122434"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b19",
    "name": "DJ",
    "data": {
      "name": "DJ",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": false,
          "values": [
            121612
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "122547"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b11",
    "name": "Entertainer",
    "data": {
      "name": "Entertainer",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": false,
          "values": [
            16698,
            16702,
            16709,
            16713,
            149665,
            121612,
            137811
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "485232",
        "149981",
        "122434",
        "122479"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b07",
    "name": "Fishermen",
    "data": {
      "name": "Fishermen",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": false,
          "values": [
            39397
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "122444"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "6f34f",
    "name": "Fitness Trainer",
    "data": {
      "name": "Fitness Trainer",
      "simCount": 2,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478653
          ],
          "rawType": 1
        },
        {
          "type": "skill",
          "required": true,
          "values": [
            16659
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "122422",
        "122483",
        "121923",
        "486554"
      ],
      "outfit": {
        "mode": "custom"
      },
      "index": 0
    }
  },
  {
    "key": "76b09",
    "name": "Friendly Sim",
    "data": {
      "name": "Friendly Sim",
      "simCount": 3,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "122422"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b17",
    "name": "Gamer",
    "data": {
      "name": "Gamer",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "122439",
        "380467"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "6f356",
    "name": "Guest",
    "data": {
      "name": "Guest",
      "simCount": 6,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "122422",
        "122484",
        "122480",
        "122469",
        "122479"
      ],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "6f5bd",
    "name": "Host",
    "data": {
      "name": "Host",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "122483",
        "122422",
        "122443",
        "401371",
        "122445"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b04",
    "name": "Mean Chef",
    "data": {
      "name": "Mean Chef",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": true,
          "values": [
            16701,
            16705,
            104198
          ],
          "rawType": 0
        },
        {
          "type": "fame",
          "required": false,
          "values": [
            3
          ],
          "rawType": 7
        }
      ],
      "activities": [
        "122480",
        "462612",
        "121698",
        "486117"
      ],
      "outfit": {
        "mode": "custom"
      },
      "index": 0
    }
  },
  {
    "key": "6f366",
    "name": "Musician",
    "data": {
      "name": "Musician",
      "simCount": 2,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b1a",
    "name": "Outdoor Collector",
    "data": {
      "name": "Outdoor Collector",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": true,
          "values": [
            27914
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "462644",
        "129789"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "6f354",
    "name": "Outdoor Enthusiast",
    "data": {
      "name": "Outdoor Enthusiast",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            27914
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "462634",
        "462635"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "6f353",
    "name": "Park Ranger",
    "data": {
      "name": "Park Ranger",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "76b0a",
    "name": "Popular Sim",
    "data": {
      "name": "Popular Sim",
      "simCount": 3,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "76b0d",
    "name": "Rebel Sim",
    "data": {
      "name": "Rebel Sim",
      "simCount": 3,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "485235"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  },
  {
    "key": "6f34d",
    "name": "Retreat Guest",
    "data": {
      "name": "Retreat Guest",
      "simCount": 6,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478631
          ],
          "rawType": 1
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "6f34e",
    "name": "Retreat Leader",
    "data": {
      "name": "Retreat Leader",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478652
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "122422",
        "122483",
        "122450",
        "486554"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "6f352",
    "name": "Romantic Host",
    "data": {
      "name": "Romantic Host",
      "simCount": 2,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478656
          ],
          "rawType": 1
        }
      ],
      "activities": [
        "122422",
        "122483",
        "122450"
      ],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "76b0f",
    "name": "Senior",
    "data": {
      "name": "Senior",
      "simCount": 6,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            64
          ],
          "rawType": 5
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "6f351",
    "name": "Singles",
    "data": {
      "name": "Singles",
      "simCount": 8,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        },
        {
          "type": "trait",
          "required": false,
          "values": [
            478655
          ],
          "rawType": 1
        },
        {
          "type": "relationship",
          "required": true,
          "values": [],
          "rawType": 13
        }
      ],
      "activities": [
        "462656"
      ],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "76b0c",
    "name": "Sporty Sim",
    "data": {
      "name": "Sporty Sim",
      "simCount": 3,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "128505",
        "121923"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "6f350",
    "name": "Staff",
    "data": {
      "name": "Staff",
      "simCount": 2,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "122483"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "6f364",
    "name": "Teacher",
    "data": {
      "name": "Teacher",
      "simCount": 1,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            112
          ],
          "rawType": 5
        }
      ],
      "activities": [
        "481435",
        "482767"
      ],
      "outfit": {
        "mode": "category"
      },
      "index": 0
    }
  },
  {
    "key": "76b10",
    "name": "Visitor",
    "data": {
      "name": "Visitor",
      "simCount": 3,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        }
      ],
      "activities": [],
      "outfit": {
        "mode": "none"
      },
      "index": 0
    }
  },
  {
    "key": "76b0e",
    "name": "Writer",
    "data": {
      "name": "Writer",
      "simCount": 2,
      "criteria": [
        {
          "type": "age",
          "required": true,
          "values": [
            120
          ],
          "rawType": 5
        },
        {
          "type": "skill",
          "required": false,
          "values": [
            16714
          ],
          "rawType": 0
        }
      ],
      "activities": [
        "122440"
      ],
      "outfit": {
        "mode": "style"
      },
      "index": 0
    }
  }
],
};
