/**
 * Small-business perk trait id -> display name. Generated by
 * scripts/diagnostics/buildStockBusinessPerks.ts. Perks are stored as TRAITS on
 * the business OWNER sim (confirmed: owners in Slot_10312029 carry these in
 * traitIds), so detect them via the sim's traitIds — same pattern as earned
 * degrees. Names are prettified tuning codenames (no inline display name in the
 * tuning). DO NOT EDIT BY HAND.
 */
export const STOCK_BUSINESS_PERKS: Record<string, string> = {
  '0x619ce': "Arsonist",
  '0x62f07': "Bartering",
  '0x62f08': "Customer Appreciation Day",
  '0x5d4a7': "Customer Sway",
  '0x62f02': "Employee Tip",
  '0x5ca7d': "Fake Bill Payment",
  '0x5d4a6': "Inspire With Business Story",
  '0x6da98': "Muscle Memory",
  '0x62f06': "Simo Coin",
  '0x62f04': "Store Pheromone",
  '0x6da99': "Tip Jar",
  '0x62f05': "Ultrasonic Whistle",
  '0x6da9a': "Viral Social Media",
  '0x62f03': "White Collar Robbery",
  '0x5ca7c': "Wutant Boost",
};

const PERK_SET = new Set(Object.keys(STOCK_BUSINESS_PERKS));
/** True if a trait id (hex '0x…') is a small-business perk trait. */
export function isBusinessPerkTrait(id: string): boolean { return PERK_SET.has(id.toLowerCase()); }
/** Resolve the small-business perk names from a sim's full trait id list. */
export function businessPerksFromTraits(traitIds: Array<bigint | string>): string[] {
  const out: string[] = [];
  for (const t of traitIds) {
    const id = (typeof t === 'bigint' ? '0x' + t.toString(16) : t).toLowerCase();
    if (PERK_SET.has(id)) out.push(STOCK_BUSINESS_PERKS[id]);
  }
  return out;
}

/**
 * Small-business alignment level (1–7) → in-game label. From the "Set Small
 * Business Alignment…" menu (B&H). Level 1 = most Nefarious, 7 = most Virtuous;
 * 4 is the Neutral center. The level comes from the owner's hidden
 * trait_SmallBusiness_Reputation_N (see parser/smallBusinesses alignmentFromTraits).
 */
export const SMALL_BUSINESS_ALIGNMENT_LABEL: Record<number, string> = {
  1: 'Nefarious', 2: 'Underground', 3: 'Illicit', 4: 'Neutral',
  5: 'Lawful', 6: 'Scrupulous', 7: 'Virtuous',
};
/** Label for a small-business alignment level (1–7), or null when unset. */
export function smallBusinessAlignmentLabel(level: number | null): string | null {
  return level == null ? null : (SMALL_BUSINESS_ALIGNMENT_LABEL[level] ?? `Level ${level}`);
}

/**
 * Small-business renown rank (0–5) → in-game label. The rank comes from the
 * owner's hidden trait_SmallBusiness_Rank_N (see parser/smallBusinesses
 * renownRankFromTraits). Names confirmed in-game.
 */
export const SMALL_BUSINESS_RANK_LABEL: Record<number, string> = {
  0: 'Garage Business', 1: 'Hopeful Hustle', 2: 'Striving Startup',
  3: 'Neighborhood Gem', 4: 'Community Staple', 5: 'Local Legend',
};
/** Label for a small-business renown rank (0–5), or null when unset. */
export function smallBusinessRankLabel(rank: number | null): string | null {
  return rank == null ? null : (SMALL_BUSINESS_RANK_LABEL[rank] ?? `Rank ${rank}`);
}
