/**
 * Stock holiday DEFAULT traditions, keyed by holiday_type (hex, no 0x) →
 * tradition tuning ids (hex, no 0x). Generated by
 * scripts/diagnostics/buildStockHolidayTraditions.ts from the
 * HolidayDefinitionTuning <L n="traditions"> lists. DO NOT EDIT BY HAND.
 *
 * Used to show the effective traditions for holidays the player hasn't
 * customized (the save only stores a traditions list when modified).
 */
export const STOCK_HOLIDAY_TRADITIONS: Record<string, string[]> = {
  '2c77b': ['2c775', '2c75e', '2c768', '2c75f', '2c769'],
  '2c77c': ['2c760', '2c761', '2c76b'],
  '2c77d': ['2c775', '2c774', '2c773', '2c772'],
  '2c77e': ['2c775', '2c778', '2c75f', '2d145'],
  '2c7e5': ['2c7e3'],
  '2c7e6': ['2c822'],
  '2c7e7': ['2c7f8'],
  '2c7e8': ['2c7f6'],
  '2c7e9': ['2c817'],
  '2c7ea': ['2c80f'],
  '2c7eb': ['2c819'],
  '2c7ed': ['2c812'],
};
