/**
 * Holiday tradition id -> display name. Generated by
 * scripts/diagnostics/buildStockTraditions.ts from a Holiday Tradition tuning
 * export; names are EA's enabled_display_name. Wedding situationActivity
 * tunings (My Wedding Stories) are excluded. DO NOT EDIT BY HAND.
 */
export const STOCK_TRADITIONS: Record<string, string> = {
  '0x2c75e': "Festive Spirit",
  '0x2c75f': "Grand Meal",
  '0x2c760': "Romantic Spirit",
  '0x2c761': "Give Flowers",
  '0x2c762': "Light Menorah",
  '0x2c763': "Sports TV",
  '0x2c764': "Air Grievances",
  '0x2c765': "Attend Holiday Ceremony",
  '0x2c766': "Give Funny Gift",
  '0x2c767': "Invite Guests",
  '0x2c768': "Open Presents",
  '0x2c769': "Father Winter",
  '0x2c76a': "Give Romantic Gifts",
  '0x2c76b': "Go on a Date",
  '0x2c76c': "Light Kinara",
  '0x2c76d': "Watch Romantic TV",
  '0x2c76e': "Remembrance",
  '0x2c76f': "Give Mean Gift",
  '0x2c770': "Polar Bear Plunge",
  '0x2c772': "Countdown to Midnight",
  '0x2c773': "Make Resolutions",
  '0x2c774': "Party Spirit",
  '0x2c775': "Decorate",
  '0x2c776': "Festive Lighting",
  '0x2c777': "Gardening",
  '0x2c778': "Holiday Gnomes",
  '0x2c7e3': "Purchase a Lottery Ticket",
  '0x2c7f6': "Shopping Rebate",
  '0x2c7f8': "Free Food and Drinks",
  '0x2c80f': "Fighting",
  '0x2c812': "Talk Like a Pirate",
  '0x2c817': "Mischief Spirit",
  '0x2c819': "Skill Improvement",
  '0x2c822': "TV Season Premiere",
  '0x2cc5d': "Give Gifts",
  '0x2d144': "Spooky Spirit",
  '0x2d145': "Thankful Spirit",
  '0x2d442': "Water Fun",
  '0x2d44f': "Fire",
  '0x2d450': "Exercise",
  '0x2d451': "Drinking",
  '0x2d452': "Baking",
  '0x2d453': "Fasting",
  '0x2d454': "Go on a Vacation or Travel",
  '0x2d456': "Tell Stories",
  '0x2d457': "Games",
  '0x2d458': "Cleaning",
  '0x2d459': "Streaking",
  '0x2d45a': "Art & Music Spirit",
  '0x2d45b': "Bar-B-Que",
  '0x2d4c9': "Egg Hunt",
  '0x2d4ca': "Appreciate an Object",
  '0x2dc37': "Trick or Treat",
  '0x2dc3e': "Wear Costumes",
  '0x2dd80': "Flower Bunny",
  '0x2e825': "Fireworks",
};

/** Resolve a tradition tuning id (bigint) to its display name, or null. */
export function resolveTradition(id: bigint): string | null {
  return STOCK_TRADITIONS['0x' + id.toString(16).toLowerCase()] ?? null;
}
