// The holidays EA puts on the calendar, keyed by holiday_type (the save's
// Holiday tuning ID) as lowercase hex without the 0x prefix. Generated by
// scripts/diagnostics/buildStockHolidays.ts from the HolidayDefinitionTuning
// files. DO NOT EDIT BY HAND.
//
// The save stores a Holiday record only for a holiday the player has edited, so
// an untouched stock holiday arrives as a bare calendar placement and takes its
// name and icon from here. A save that DOES carry a name overrides this map —
// including a localised one, so a French save's Winterfest reads Noël.
//
// EA's eight SURPRISE holidays are deliberately absent: they fire as events and
// are never written into the save's calendar. See the generator's header.
//
// `icon` is the icon ResourceKey's instance hex, which is also its filename in
// public/holiday-icons/.

export interface StockHoliday {
  name: string;
  icon: string;
}

export const STOCK_HOLIDAYS: Record<string, StockHoliday> = {
  '2c77b': { name: "Winterfest",     icon: '5fdbcbae767e3274' },
  '2c77c': { name: "Love Day",       icon: '0e9d1ecfaa889895' },
  '2c77d': { name: "New Year's Eve", icon: '14ed6bfdc9e9bc46' },
  '2c77e': { name: "Harvestfest",    icon: '573597ddcdbad0ea' },
};

export function resolveStockHoliday(holidayType: bigint): StockHoliday | null {
  return STOCK_HOLIDAYS[holidayType.toString(16).toLowerCase()] ?? null;
}
