/**
 * Stock holiday DEFAULTS (time off + decoration theme), generated by
 * scripts/diagnostics/buildStockHolidayDefaults.ts from HolidayDefinitionTuning.
 * Used for holidays the player hasn't customized (the save only stores a record
 * — with f4 time_off_work / f5 time_off_school / f7 decoration_preset — when
 * modified). DO NOT EDIT BY HAND.
 */

/** Decoration-preset id (decimal string, as stored in the holiday record's f7) -> display name. */
export const HOLIDAY_DECORATION_NAMES: Record<string, string> = {
  "184879": "Winterfest",
  "184960": "Love Day",
  "184961": "Harvestfest",
  "184962": "New Year's",
  "191123": "Spring",
  "191127": "Spooky"
};

/** Resolve a decoration-preset id to its theme name, or null when none/unknown. */
export function holidayDecorationName(presetId: string | null): string | null {
  if (!presetId || presetId === '0') return null;
  return HOLIDAY_DECORATION_NAMES[presetId] ?? `Theme #${presetId}`;
}

/** holiday_type hex -> default day-off (work/school) for stock holidays. */
export const STOCK_HOLIDAY_TIME_OFF: Record<string, { work: boolean; school: boolean }> = {
  "2c77b": {
    "work": true,
    "school": true
  },
  "2c77d": {
    "work": true,
    "school": true
  },
  "2c77e": {
    "work": true,
    "school": true
  }
};

/** holiday_type hex -> default decoration-preset id (decimal string) for stock holidays. */
export const STOCK_HOLIDAY_DECORATION: Record<string, string> = {
  "2c77b": "184879",
  "2c77c": "184960",
  "2c77d": "184962",
  "2c77e": "184961"
};
