/**
 * NPC service/role hidden-trait catalog: trait tuning ID (hex) → role name.
 *
 * Generated by scripts/diagnostics/buildProvenanceCatalogs.ts from is<Role> hidden
 * traits across all SimTemplateTuning files (22 roles). A sim carrying one of
 * these in its parsed traitIds is the game's current mailman/grim reaper/etc — used to
 * sub-label an EA household as a service NPC. Excludes gender-customization + skill-mastery
 * traits (not service roles). Key format matches STOCK_TRAITS ('0x' + id.toString(16)).
 */
export const ROLE_TRAITS: Record<string, string> = {
  '0x2955': "Pizza Delivery",
  '0x41d3': "Grim Reaper",
  '0x41d4': "Maid",
  '0x41d5': "Mailman",
  '0x19818': "Bear",
  '0x1a8d8': "Forest Ranger",
  '0x1b830': "Alien Pollinator",
  '0x1d374': "Massage Therapist",
  '0x1ea5e': "Chalet Gardens Ghost",
  '0x1f9c8': "Repair",
  '0x220f9': "Restaurant Critic",
  '0x22267': "Tragic Clown",
  '0x22a1e': "Nanny",
  '0x23eb1': "Butler",
  '0x2615d': "City Repair",
  '0x2615f': "Statue Busker",
  '0x3800d': "School Ghost",
  '0x4a2c5': "Ranch Hand",
  '0x55940': "Premade PO",
  '0x635ae': "Emit",
  '0x66f71': "Burglar",
  '0x71fa0': "Robin Hood",
};
