/**
 * Hidden getaway-NPC role traits referenced by custom-venue role criteria.
 * id -> confirmed in-game display_name (from the TraitTuning STBL comment) + the
 * icon's ResourceKey instance. The PNG files are named by the trait id
 * (/trait-icons/<traitIdHex>.png, written by extractIconsFromHTML.ts); `icon` is
 * the has-icon flag + exact ResourceKey provenance, not the filename.
 * Generated by scripts/diagnostics/buildVenueTraits.ts from ~/Documents/Traits.
 * DO NOT EDIT BY HAND. These are distinct from the CAS traits in stockTraits.ts.
 */
export interface StockVenueTrait { name: string; icon: string | null }
export const STOCK_VENUE_TRAITS: Record<string, StockVenueTrait> = {
  '0x74da5': { name: "Seasoned Camp Counselor", icon: '4ce05be1ad7b05a6' },
  '0x74da6': { name: "Seasoned Camp Director", icon: '8a0aa837ae0eb9a4' },
  '0x74da4': { name: "Seasoned Camper", icon: 'bc3928972bcfdcc0' },
  '0x74da7': { name: "Seasoned Fitness Retreat Guest", icon: '80da91b71889d02a' },
  '0x74dbd': { name: "Seasoned Fitness Trainer", icon: '45902bc62a2ea5bc' },
  '0x74dbc': { name: "Seasoned Retreat Leader", icon: '8168a0db4be13666' },
  '0x74dc0': { name: "Seasoned Romantic Host", icon: '155ee1e44a72b9a0' },
  '0x74dbf': { name: "Seasoned Romantic Single", icon: '5b36c3df6316da2d' },
};
